name       : python-feedgenerator
version    : 2.0.0
release    : 4
source     :
    - https://pypi.io/packages/source/f/feedgenerator/feedgenerator-2.0.0.tar.gz : 6836d456b8b0edbc5b6d3a42d1be852cebd43d2f28af4ff51789eb295f1860e2
license    : BSD
component  : programming.python
summary    : Standalone version of django.utils.feedgenerator
description: |
    Syndication feed generation library -- used for generating RSS, etc.
builddeps  :
    - pkgconfig(python3)
    - python-pytz
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    needs python-pytest-cov packaged
#    %python3_test pytest3
