name       : python-feedgenerator
version    : 1.9
release    : 3
source     :
    - https://files.pythonhosted.org/packages/eb/02/7069b3dbc6ea92f034e07f9f9adc2193cd02d1aedf2cf9ec71150102a964/feedgenerator-1.9.tar.gz : 5ae05daa9cfa47fa406ee4744d0b7fa1c8a05a7a47ee0ad328ddf55327cfb106
license    : BSD
component  : programming.python
summary    : Standalone version of django.utils.feedgenerator
description: |
    Syndication feed generation library -- used for generating RSS, etc.
builddeps  :
    - pkgconfig(python3)
    - python-pytz
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
